/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155BurnableLite } from "./ERC1155BurnableLite";
export type { ERC1155Permit } from "./ERC1155Permit";
export type { ERC1155Royalty } from "./ERC1155Royalty";
export type { ERC1155SupplyLite } from "./ERC1155SupplyLite";
export type { ERC1155URIStorage } from "./ERC1155URIStorage";
export type { IERC1155Permit } from "./IERC1155Permit";
