/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extensions from "./extensions";
export type { extensions };
export type { ERC721Lite } from "./ERC721Lite";
export type { IERC721Lite } from "./IERC721Lite";
