/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IGovernanceInterface extends utils.Interface {
  functions: {
    "acceptedPayments(address)": FunctionFragment;
    "marketplace()": FunctionFragment;
    "owner()": FunctionFragment;
    "treasury()": FunctionFragment;
    "verifier()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "acceptedPayments"
      | "marketplace"
      | "owner"
      | "treasury"
      | "verifier"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptedPayments",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "marketplace",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "acceptedPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;

  events: {
    "PaymentUpdated(address,bool)": EventFragment;
    "TreasuryUpdated(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PaymentUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TreasuryUpdated"): EventFragment;
}

export interface PaymentUpdatedEventObject {
  token_: string;
  registed: boolean;
}
export type PaymentUpdatedEvent = TypedEvent<
  [string, boolean],
  PaymentUpdatedEventObject
>;

export type PaymentUpdatedEventFilter = TypedEventFilter<PaymentUpdatedEvent>;

export interface TreasuryUpdatedEventObject {
  from_: string;
  to_: string;
}
export type TreasuryUpdatedEvent = TypedEvent<
  [string, string],
  TreasuryUpdatedEventObject
>;

export type TreasuryUpdatedEventFilter = TypedEventFilter<TreasuryUpdatedEvent>;

export interface IGovernance extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IGovernanceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptedPayments(
      token_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    marketplace(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    treasury(overrides?: CallOverrides): Promise<[string]>;

    verifier(overrides?: CallOverrides): Promise<[string]>;
  };

  acceptedPayments(
    token_: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  marketplace(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  treasury(overrides?: CallOverrides): Promise<string>;

  verifier(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    acceptedPayments(
      token_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    marketplace(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    treasury(overrides?: CallOverrides): Promise<string>;

    verifier(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "PaymentUpdated(address,bool)"(
      token_?: PromiseOrValue<string> | null,
      registed?: null
    ): PaymentUpdatedEventFilter;
    PaymentUpdated(
      token_?: PromiseOrValue<string> | null,
      registed?: null
    ): PaymentUpdatedEventFilter;

    "TreasuryUpdated(address,address)"(
      from_?: PromiseOrValue<string> | null,
      to_?: PromiseOrValue<string> | null
    ): TreasuryUpdatedEventFilter;
    TreasuryUpdated(
      from_?: PromiseOrValue<string> | null,
      to_?: PromiseOrValue<string> | null
    ): TreasuryUpdatedEventFilter;
  };

  estimateGas: {
    acceptedPayments(
      token_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    marketplace(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    treasury(overrides?: CallOverrides): Promise<BigNumber>;

    verifier(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptedPayments(
      token_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    marketplace(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    treasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    verifier(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
