/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace ReceiptUtil {
  export type UserStruct = {
    addr: PromiseOrValue<string>;
    v: PromiseOrValue<BigNumberish>;
    deadline: PromiseOrValue<BigNumberish>;
    r: PromiseOrValue<BytesLike>;
    s: PromiseOrValue<BytesLike>;
  };

  export type UserStructOutput = [string, number, BigNumber, string, string] & {
    addr: string;
    v: number;
    deadline: BigNumber;
    r: string;
    s: string;
  };

  export type HeaderStruct = {
    buyer: ReceiptUtil.UserStruct;
    seller: ReceiptUtil.UserStruct;
    nftContract: PromiseOrValue<string>;
    paymentToken: PromiseOrValue<string>;
  };

  export type HeaderStructOutput = [
    ReceiptUtil.UserStructOutput,
    ReceiptUtil.UserStructOutput,
    string,
    string
  ] & {
    buyer: ReceiptUtil.UserStructOutput;
    seller: ReceiptUtil.UserStructOutput;
    nftContract: string;
    paymentToken: string;
  };

  export type ItemStruct = {
    amount: PromiseOrValue<BigNumberish>;
    tokenId: PromiseOrValue<BigNumberish>;
    unitPrice: PromiseOrValue<BigNumberish>;
    tokenURI: PromiseOrValue<string>;
  };

  export type ItemStructOutput = [BigNumber, BigNumber, BigNumber, string] & {
    amount: BigNumber;
    tokenId: BigNumber;
    unitPrice: BigNumber;
    tokenURI: string;
  };

  export type ReceiptStruct = {
    header: ReceiptUtil.HeaderStruct;
    item: ReceiptUtil.ItemStruct;
    nonce: PromiseOrValue<BigNumberish>;
    deadline: PromiseOrValue<BigNumberish>;
  };

  export type ReceiptStructOutput = [
    ReceiptUtil.HeaderStructOutput,
    ReceiptUtil.ItemStructOutput,
    BigNumber,
    BigNumber
  ] & {
    header: ReceiptUtil.HeaderStructOutput;
    item: ReceiptUtil.ItemStructOutput;
    nonce: BigNumber;
    deadline: BigNumber;
  };

  export type BulkStruct = {
    amounts: PromiseOrValue<BigNumberish>[];
    tokenIds: PromiseOrValue<BigNumberish>[];
    unitPrices: PromiseOrValue<BigNumberish>[];
    tokenURIs: PromiseOrValue<string>[];
  };

  export type BulkStructOutput = [
    BigNumber[],
    BigNumber[],
    BigNumber[],
    string[]
  ] & {
    amounts: BigNumber[];
    tokenIds: BigNumber[];
    unitPrices: BigNumber[];
    tokenURIs: string[];
  };

  export type BulkReceiptStruct = {
    header: ReceiptUtil.HeaderStruct;
    bulk: ReceiptUtil.BulkStruct;
    nonce: PromiseOrValue<BigNumberish>;
    deadline: PromiseOrValue<BigNumberish>;
  };

  export type BulkReceiptStructOutput = [
    ReceiptUtil.HeaderStructOutput,
    ReceiptUtil.BulkStructOutput,
    BigNumber,
    BigNumber
  ] & {
    header: ReceiptUtil.HeaderStructOutput;
    bulk: ReceiptUtil.BulkStructOutput;
    nonce: BigNumber;
    deadline: BigNumber;
  };
}

export interface IMarketplaceInterface extends utils.Interface {
  functions: {
    "initialize(address,uint256)": FunctionFragment;
    "pause()": FunctionFragment;
    "redeem((((address,uint8,uint256,bytes32,bytes32),(address,uint8,uint256,bytes32,bytes32),address,address),(uint256,uint256,uint256,string),uint256,uint256),bytes)": FunctionFragment;
    "redeemBulk((((address,uint8,uint256,bytes32,bytes32),(address,uint8,uint256,bytes32,bytes32),address,address),(uint256[],uint256[],uint256[],string[]),uint256,uint256),bytes)": FunctionFragment;
    "unpause()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "initialize"
      | "pause"
      | "redeem"
      | "redeemBulk"
      | "unpause"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "initialize",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [ReceiptUtil.ReceiptStruct, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemBulk",
    values: [ReceiptUtil.BulkReceiptStruct, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "redeemBulk", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;

  events: {
    "BulkRedeemed(address,address,uint256[],address,uint256)": EventFragment;
    "ItemRedeemed(address,address,uint256,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BulkRedeemed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ItemRedeemed"): EventFragment;
}

export interface BulkRedeemedEventObject {
  nftContract: string;
  buyer: string;
  tokenIds: BigNumber[];
  paymentToken: string;
  total: BigNumber;
}
export type BulkRedeemedEvent = TypedEvent<
  [string, string, BigNumber[], string, BigNumber],
  BulkRedeemedEventObject
>;

export type BulkRedeemedEventFilter = TypedEventFilter<BulkRedeemedEvent>;

export interface ItemRedeemedEventObject {
  nftContract: string;
  buyer: string;
  tokenId: BigNumber;
  paymentToken: string;
  total: BigNumber;
}
export type ItemRedeemedEvent = TypedEvent<
  [string, string, BigNumber, string, BigNumber],
  ItemRedeemedEventObject
>;

export type ItemRedeemedEventFilter = TypedEventFilter<ItemRedeemedEvent>;

export interface IMarketplace extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IMarketplaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    initialize(
      admin_: PromiseOrValue<string>,
      serviceFeeRightShiftBit_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    redeem(
      receipt_: ReceiptUtil.ReceiptStruct,
      signature_: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    redeemBulk(
      receipt_: ReceiptUtil.BulkReceiptStruct,
      signature_: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  initialize(
    admin_: PromiseOrValue<string>,
    serviceFeeRightShiftBit_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  redeem(
    receipt_: ReceiptUtil.ReceiptStruct,
    signature_: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  redeemBulk(
    receipt_: ReceiptUtil.BulkReceiptStruct,
    signature_: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    initialize(
      admin_: PromiseOrValue<string>,
      serviceFeeRightShiftBit_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    pause(overrides?: CallOverrides): Promise<void>;

    redeem(
      receipt_: ReceiptUtil.ReceiptStruct,
      signature_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    redeemBulk(
      receipt_: ReceiptUtil.BulkReceiptStruct,
      signature_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "BulkRedeemed(address,address,uint256[],address,uint256)"(
      nftContract?: PromiseOrValue<string> | null,
      buyer?: PromiseOrValue<string> | null,
      tokenIds?: null,
      paymentToken?: null,
      total?: null
    ): BulkRedeemedEventFilter;
    BulkRedeemed(
      nftContract?: PromiseOrValue<string> | null,
      buyer?: PromiseOrValue<string> | null,
      tokenIds?: null,
      paymentToken?: null,
      total?: null
    ): BulkRedeemedEventFilter;

    "ItemRedeemed(address,address,uint256,address,uint256)"(
      nftContract?: PromiseOrValue<string> | null,
      buyer?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      paymentToken?: null,
      total?: null
    ): ItemRedeemedEventFilter;
    ItemRedeemed(
      nftContract?: PromiseOrValue<string> | null,
      buyer?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      paymentToken?: null,
      total?: null
    ): ItemRedeemedEventFilter;
  };

  estimateGas: {
    initialize(
      admin_: PromiseOrValue<string>,
      serviceFeeRightShiftBit_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    redeem(
      receipt_: ReceiptUtil.ReceiptStruct,
      signature_: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    redeemBulk(
      receipt_: ReceiptUtil.BulkReceiptStruct,
      signature_: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    initialize(
      admin_: PromiseOrValue<string>,
      serviceFeeRightShiftBit_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    redeem(
      receipt_: ReceiptUtil.ReceiptStruct,
      signature_: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    redeemBulk(
      receipt_: ReceiptUtil.BulkReceiptStruct,
      signature_: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
