/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as extensions from "./extensions";
export { ERC1155Lite__factory } from "./ERC1155Lite__factory";
export { IERC1155Lite__factory } from "./IERC1155Lite__factory";
