/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721BurnableLite } from "./ERC721BurnableLite";
export type { ERC721Permit } from "./ERC721Permit";
export type { ERC721Royalty } from "./ERC721Royalty";
export type { ERC721URIStorageLite } from "./ERC721URIStorageLite";
export type { IERC721Permit } from "./IERC721Permit";
