export const STORAGE_KEY = {
    RUNNING_GAME: "RUNNING_GAME",
    PLAY_MODE: "PLAY_MODE",
    PROVIDER_LOGIN: "PROVIDER_LOGIN",
    WALLET_NETWORK: "WALLET_NETWORK",
    CURRENT_SYMBOL: "CURRENT_SYMBOL",
    WALLET_INFO: "WALLET_INFO",
}
