/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface GasTestInterface extends utils.Interface {
  functions: {
    "multiply(uint256,uint256,uint256)": FunctionFragment;
    "multiply2(uint256,uint256,uint256)": FunctionFragment;
    "multiply3(uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "multiply" | "multiply2" | "multiply3"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "multiply",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multiply2",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multiply3",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "multiply", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "multiply2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "multiply3", data: BytesLike): Result;

  events: {};
}

export interface GasTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GasTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    multiply(
      val_: PromiseOrValue<BigNumberish>,
      mul_: PromiseOrValue<BigNumberish>,
      div_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    multiply2(
      val_: PromiseOrValue<BigNumberish>,
      mul_: PromiseOrValue<BigNumberish>,
      div_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    multiply3(
      val_: PromiseOrValue<BigNumberish>,
      n_bits_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  multiply(
    val_: PromiseOrValue<BigNumberish>,
    mul_: PromiseOrValue<BigNumberish>,
    div_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  multiply2(
    val_: PromiseOrValue<BigNumberish>,
    mul_: PromiseOrValue<BigNumberish>,
    div_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  multiply3(
    val_: PromiseOrValue<BigNumberish>,
    n_bits_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    multiply(
      val_: PromiseOrValue<BigNumberish>,
      mul_: PromiseOrValue<BigNumberish>,
      div_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    multiply2(
      val_: PromiseOrValue<BigNumberish>,
      mul_: PromiseOrValue<BigNumberish>,
      div_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    multiply3(
      val_: PromiseOrValue<BigNumberish>,
      n_bits_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    multiply(
      val_: PromiseOrValue<BigNumberish>,
      mul_: PromiseOrValue<BigNumberish>,
      div_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    multiply2(
      val_: PromiseOrValue<BigNumberish>,
      mul_: PromiseOrValue<BigNumberish>,
      div_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    multiply3(
      val_: PromiseOrValue<BigNumberish>,
      n_bits_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    multiply(
      val_: PromiseOrValue<BigNumberish>,
      mul_: PromiseOrValue<BigNumberish>,
      div_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    multiply2(
      val_: PromiseOrValue<BigNumberish>,
      mul_: PromiseOrValue<BigNumberish>,
      div_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    multiply3(
      val_: PromiseOrValue<BigNumberish>,
      n_bits_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
