/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155BurnableLite__factory } from "./ERC1155BurnableLite__factory";
export { ERC1155Permit__factory } from "./ERC1155Permit__factory";
export { ERC1155Royalty__factory } from "./ERC1155Royalty__factory";
export { ERC1155SupplyLite__factory } from "./ERC1155SupplyLite__factory";
export { ERC1155URIStorage__factory } from "./ERC1155URIStorage__factory";
export { IERC1155Permit__factory } from "./IERC1155Permit__factory";
