/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extensions from "./extensions";
export type { extensions };
export type { ERC1155Lite } from "./ERC1155Lite";
export type { IERC1155Lite } from "./IERC1155Lite";
