/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as token from "./token";
export type { token };
export type { IMarketplaceIntegratable } from "./IMarketplaceIntegratable";
export type { INFTBase } from "./INFTBase";
export type { ITokenFreezable } from "./ITokenFreezable";
export type { MarketplaceIntegratable } from "./MarketplaceIntegratable";
export type { NFTBase } from "./NFTBase";
export type { NFTRoyalty } from "./NFTRoyalty";
export type { TokenFreezable } from "./TokenFreezable";
