/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IMarketplaceIntegratable,
  IMarketplaceIntegratableInterface,
} from "../../../contracts/base/IMarketplaceIntegratable";

const _abi = [
  {
    inputs: [],
    name: "MPI__DelegatecallFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "MPI__NonZeroAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "MPI__Unauthorized",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "newAddr",
        type: "address",
      },
    ],
    name: "GovernanceUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "addr_",
        type: "address",
      },
    ],
    name: "updateGovernance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IMarketplaceIntegratable__factory {
  static readonly abi = _abi;
  static createInterface(): IMarketplaceIntegratableInterface {
    return new utils.Interface(_abi) as IMarketplaceIntegratableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMarketplaceIntegratable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IMarketplaceIntegratable;
  }
}
