/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  INFTBase,
  INFTBaseInterface,
} from "../../../contracts/base/INFTBase";

const _abi = [
  {
    inputs: [],
    name: "TYPE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class INFTBase__factory {
  static readonly abi = _abi;
  static createInterface(): INFTBaseInterface {
    return new utils.Interface(_abi) as INFTBaseInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INFTBase {
    return new Contract(address, _abi, signerOrProvider) as INFTBase;
  }
}
