/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  MarketplaceIntegratable,
  MarketplaceIntegratableInterface,
} from "../../../contracts/base/MarketplaceIntegratable";

const _abi = [
  {
    inputs: [],
    name: "MPI__DelegatecallFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "MPI__NonZeroAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "MPI__Unauthorized",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "newAddr",
        type: "address",
      },
    ],
    name: "GovernanceUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    inputs: [],
    name: "admin",
    outputs: [
      {
        internalType: "contract IGovernance",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "addr_",
        type: "address",
      },
    ],
    name: "updateGovernance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class MarketplaceIntegratable__factory {
  static readonly abi = _abi;
  static createInterface(): MarketplaceIntegratableInterface {
    return new utils.Interface(_abi) as MarketplaceIntegratableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MarketplaceIntegratable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as MarketplaceIntegratable;
  }
}
